### ISSUE TITLE
Using `knitr::include_graphics()`

### ISSUE THREAD

**Issue by samanthacsik** [Openscapes/website-new#11]
Motivated by the [github illustrated series](https://www.openscapes.org/blog/2022/05/27/github-illustrated-series/) art not showing up when embedded with html (not sure why, almost all other blog posts were rendering just fine) -- I decided to switch to `knitr::include_graphics("file/path/to/img.png")`

Markdown syntax, `![]()`, is clean, but alt text is rendering on the page, which makes for some very text-heavy web pages. Using knitr allows us to use code chunk options (e.g. `fig-align`, `fig-alt`), which are easy to read/add to (and alt text isn't rendered on the page)

See this blog post file for examples of `knitr` syntax for inserting images: <https://github.com/Openscapes/website-new/blob/main/blog/2022-05-27-github-illustrated-series/index.qmd>

I've also updated main Openscapes web pages (i.e. those in the navbar) to use this syntax and crafted alt text for each. I *have not* changed blog posts or events, but think using `knitr` might be a nice approach moving forward. Only exceptions were:
- [Toward kinder science](https://github.com/Openscapes/website-new/blob/main/blog/2019-12-11-towards-kinder-science/index.qmd) (image wasn't showing up)
- [Tidy data for efficiency, reproducibility, and collaboration](https://github.com/Openscapes/website-new/blob/main/blog/2020-10-12-tidy-data/index.qmd) -- I switched to `knitr` so I could easily add alt text for all the awesome art included in this post :)
- [Personifying code](https://github.com/Openscapes/website-new/blob/main/blog/2019-01-15-personify-code/index.qmd) -- for the same reasons as the post above

**Comment by jules32** [comment]
Sounds like a good approach, thanks for digging into this Sam!

**Comment by samanthacsik** [comment]
UPDATE: looks like there's [a way to include alt text using markdown-flavored syntax](https://quarto.org/docs/authoring/markdown-basics.html#links-images), though I still really love the `knitr` option and would encourage sticking with that convention

**Comment by samanthacsik** [comment]
Started [a wiki](https://github.com/Openscapes/website-new/wiki/Adding-images) that details how to add images using `knitr::include_graphics()` :)
