### ISSUE TITLE
work culture page

### ISSUE THREAD

**Issue by jules32** [Openscapes/website-new#15]
This is a Q first for @stefaniebutland and then we can think implementation –

Fred Hutch has a page I really like: https://hutchdatascience.org/news/dasl-culture/. Our Approach Guide gets at this but I wonder if we could fork (& credit) this and add somewhere on the main webpage. Curious what you both think. Thanks!

**Comment by stefaniebutland** [comment]
I like the idea of fork & credit and add to our site. Belongs in ABOUT > How we work (new page)
