### ISSUE TITLE
statistics graphic for Impact page

### ISSUE THREAD

**Issue by jules32** [Openscapes/website-new#22]
Hi @stefaniebutland , 

Combining threads here: You said "putting stats front and center is powerful https://prereview.org/." And I liked SGCI's stats in the photo below. 

Could you please think of the stats you'd like to see (and then I can help us get them or they can be a good goal to capture later)

I'm thinking we'll make a graphic in Google Slides and add as an image to the IMPACT page that will be linked from the navbar
https://github.com/Openscapes/website-new/blob/update-copy/impact.qmd#L49

<img width="324" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/90200186-b686-4384-bd9c-254936c3cbda">

**Comment by stefaniebutland** [comment]
will do!

**Comment by stefaniebutland** [comment]
outlining ideas here first

Since 2018 (don't add end date)

- [ ] x Openscapes Champions Cohorts
- [ ] x Openscapes Mentors onboarded
- [ ] x Champions trained in Champions Program, Pathways to Open Science, Reflections
- [ ] 1 Fork of Openscapes Curriculum

resist the temptation to explain details of the numbers


Second string

- [ ] GitHub commits in Approach Guide
- [ ] contributors to the NASA Earthdata Cloud Cookbook


screenshot of prereview new website. I like the look of the bubbles under stats. Maybe testimonials could look like that (ultimately)


![Image](https://github.com/Openscapes/website-new/assets/11927811/57b46b47-6539-4e38-a483-1a6a8bcb416b)

**Comment by stefaniebutland** [comment]
## Examples of graphics
### Numbers and testimonials

Prereview new website (screenshot). I like the look of the bubbles under stats. Maybe testimonials could look like that (ultimately)

![Image](https://github.com/Openscapes/website-new/assets/11927811/57b46b47-6539-4e38-a483-1a6a8bcb416b)

### Logos

I don't love seeing heaps of colorful logos. rOpenSci made them b&w for subtlety (screenshot)

![Image](https://github.com/Openscapes/website-new/assets/11927811/cd16152f-68ed-4eae-b0be-302121a61c49)

**Comment by jules32** [comment]
Love these ideas @stefaniebutland . Here is another great example we could model after: 

https://science.nasa.gov/learners

<img width="786" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/3e5f7abc-7e5a-49f1-9f02-400d43a8e397">

**Comment by jules32** [comment]
Hi @stefaniebutland, I've iterated the Impacts page slightly ([commit](https://github.com/Openscapes/website-new/pull/20/commits/456d0b7926c918571e17322abb989c53239f1d6e)), although it still needs some help rethinking. Let's discuss Tuesday, and any ideas you have are welcome (you also @samanthacsik if you would like to tinker from here or have better ideas!).

**Comment by stefaniebutland** [comment]
First try at [numbers slide](https://docs.google.com/presentation/d/16NwuLZdl6mJZr9S7BSf04PPRL-4Lq7lkbAV5eo00C24/edit#slide=id.g185866dc5bf_0_228), to discuss Tuesday

**Comment by jules32** [comment]
We have a working png on the .index page now; to discuss with Sam about how best to represent it

**Comment by samanthacsik** [comment]
First pass at these stat boxes! 
![Screen Shot 2023-06-14 at 11 01 28 AM](https://github.com/Openscapes/website-new/assets/43836046/b7babe9c-fc0e-478f-b472-c2f91fca039e)

**Comment by jules32** [comment]
ooh I like them!!!
