### ISSUE TITLE
change events banner to blue

### ISSUE THREAD

**Issue by jules32** [Openscapes/website-new#27]
I think this would help visually link Events listing page to individual events. Current screenshots below. 

Events listing page:

<img width="1356" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/b5d6e5d7-3b2c-49fd-a9b7-959ac33389f0">

Example event page: 

<img width="1371" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/34ba379c-ad19-4e16-a170-ddbf76e437df">

**Comment by samanthacsik** [comment]
easy fix! we had that originally. do we also want to change the blog banner to the same yellow/orange color that individual posts have? e.g. 
![Screen Shot 2023-06-14 at 4 53 27 PM](https://github.com/Openscapes/website-new/assets/43836046/3674c7de-5af0-43a9-ae24-71899cad48ec)
