### ISSUE TITLE
In lieu of navbar highlighting, consider "blog" and "event" tags? 

### ISSUE THREAD

**Issue by jules32** [Openscapes/website-new#38]
Should we add "blog" and "event" tags to all the blogs and events? Yes this would mean every blog post had that same tag, but it might help the reader navigate since the top nav bar doesn't highlight as "blog" when you're on a blog. 

It might be better to wait until there's a feature to highlight the navbar when you're on a single post. But it still might be worth doing if it helps people navigate. What do you think @samanthacsik , @stefaniebutland ?

## 1st example 

If I find myself on this page, I don't really know where I am (without studying the URL). If the tags were "events" and "talk", that could help?

<img width="1366" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/65e26c6c-3f33-47c4-bc37-3f575fe3dca8">

## Second example 

Similarly, could this be "blog" "champions" "noaa-fisheries" ?

<img width="1360" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/b5a9ec91-06c0-423a-b26f-5cc4ad67c04c">

**Comment by samanthacsik** [comment]
i agree that it's difficult to tell which page you're on when you find yourself on a blog post or event -- i actually think a tag is a nice way to help differentiate...been trying to think of other alternatives, but haven't come up with anything else. Let me know if you want to proceed with this and I can add those tags!

**Comment by stefaniebutland** [comment]
Yes to keeping different colored banners AND to having `blog` and `event` tags. ***event should be singular
@samanthacsik @jules32

**Comment by jules32** [comment]
Awesome. +1 Stef. @samanthacsik would you please implement this? 

I wonder if Edit > Find In Files and regular expressions would be a way to do this without having to click into each file...

<img width="422" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/0171cdf7-8293-4f1b-a7f3-642505366fa3">

<img width="466" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/7140461c-20f8-40e5-8c61-5558b46ebc60">

**Comment by samanthacsik** [comment]
done and merged to main here: https://github.com/Openscapes/website-new/commit/64b890ba2ac53fda5ffd437fc76a8fdc10460039!
