### ISSUE TITLE
Redirecting events repo

### ISSUE THREAD

**Issue by jules32** [Openscapes/website-new#43]
We've added [redirects for all event pages](https://github.com/Openscapes/website-new/blob/main/netlify.toml#L545), which means transferring what are really blog posts from a separate repo called "events" into a subdirectory of "website-new". The redirects in the `netlify.toml` look like this: 

```
[[redirects]]
	from = "https://openscapes.github.io/events/posts/2023-05-08-reflections/"
	to = "/events/2023-05-08-reflections/"
	status = 301
```

We couldn't test this worked without first turning off the old site - openscapes.github.io/events. So:

- for https://github.com/openscapes/events
- I renamed the branch `gh-pages-deprecated`
- I went to https://github.com/Openscapes/events/settings/pages and clicked "unpublish website"
- I deleted the GitHub Action
- At that point https://openscapes.github.io/events/posts/2023-03-28-sean-kross-kyber/ gave a 404. And it's a GitHub site 404, not a netlify/openscapes quarto website 404. 
<img width="935" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/d507f4a3-664e-41eb-bbc6-19678c32c401">

This makes me wonder whether we can do redirects in this way for events, which had been at a separate site. A few thoughts come to mind: 
1. maybe we need to reinstate this separate events repo (github.com/openscapes/event ) as a website and add a redirect from this repo to openscapes.org so that these post take you to the openscapes.org site. I can test that and see if it works. 
2. How often do people look for old events?

**Comment by jules32** [comment]
OK, I've reinstated the stand-alone events site: https://openscapes.github.io/events/. 

So now, if people click on an old link, they will not be redirected but actually go to this stand-alone site, example: https://openscapes.github.io/events/posts/2023-03-28-sean-kross-kyber/. 

## Philosophical question
for @samanthacsik @stefaniebutland :

Maybe this isn't the worst? It does take them away from our main site. I'm thinking through: just how important it is for this site to redirect to the main site, because it seems like stand-alone site needs to exist lest people get a github 404. Maybe this is just the way it is and future events are part of the main site but we don't worry too much about this old site being confusing? I might be missing a way the redirects could work (redirecting from inside this stand-alone site to openscapes.org, I am not sure that would work). We could also write something across the top like this: (experimenting in a local build): 

<img width="1055" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/38ae5c37-0662-494b-a26c-41c5422a9e7a">

I'm thinking this might be the way to go, and we stop with trying to get the events redirects to work. What do you both think?

**Comment by samanthacsik** [comment]
@jules32 sorry those redirects didn't work! I wasn't sure if they would but had hoped....I think what you're describing above will work just fine -- I don't think folks will be looking for past events often, and the longer the new website is up and running, the less important this issue will become (I think).

I don't think it's worth spending too much time troubleshooting this one, but I am wondering now if this redirect might work (i.e. including the website's domain name in the "to = ")? 

```
[[redirects]]
	from = "https://openscapes.github.io/events/posts/2023-05-08-reflections/"
	to = "https://openscapes.org/events/2023-05-08-reflections/"
	status = 301
```
 
It may not be worth taking the old site down again to test -- ultimately, I think it's fine to leave it as is.

**Comment by stefaniebutland** [comment]
I agree with @jules32 suggestion and the screenshot in your comment above
> We could also write something across the top like this: (experimenting in a local build):

**Comment by jules32** [comment]
Thanks both – I've pushed the titling to the events site as in my screenshot above and we can be done with redirects!
