### ISSUE TITLE
404 https://openscapes.github.io/events/posts/2021-05-07-css-champions/css.html

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/website-new#67]
404: https://openscapes.github.io/events/posts/2021-05-07-css-champions/css.html

works: https://openscapes.org/events/2021-05-07-css-champions/index.html

now can't find what linked to the css.html. trying GitHub search

**Comment by jules32** [comment]
Looks like when we archived the old repo undeployed the whole website. https://github.com/Openscapes/events

Stef, I believe you made the repo read-only; could you temporaily reinstate it to change this url to openscapes.org/events?

<img width="326" alt="image" src="https://github.com/Openscapes/website-new/assets/5891909/c90228e4-b2cd-4ff2-aa82-b39724d3fc2e">

**Comment by stefaniebutland** [comment]
Unarchived and changed URL to https://openscapes.org/events then archived repo again (which makes it read-only).
Is it ok now?

**Comment by jules32** [comment]
Yes, thank you Stef!
